# Generated by Django 4.0.5 on 2022-06-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_persona_donador'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='utilizarNull',
            field=models.BooleanField(default=True),
        ),
    ]
