# Generated by Django 4.0.5 on 2022-06-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_persona_utilizarnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='utilizarNull',
            field=models.BooleanField(default=False),
        ),
    ]
