# Generated by Django 4.0.5 on 2022-06-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_persona_utilizarnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='utilizarNull2',
            field=models.BooleanField(null=True),
        ),
    ]
