# Generated by Django 4.0.5 on 2022-06-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_persona_utilizarnull2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='utilizarNull2',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
