# Generated by Django 4.0.5 on 2022-06-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_alter_persona_utilizarnull2'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='utilizarBlank',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
