# Generated by Django 4.0.5 on 2022-06-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_persona_utilizarblank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='utilizarBlank',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='utilizarNull',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='utilizarNull2',
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
    ]
